name: build script for flashcardapp

on:							
  push:
    branches: [ "Adrians-code" ]			

jobs:

  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		
      - name: Install GTK4
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev

      - name: build flashcardapp	
        run: make flashcardapp

      - name: Upload Executables
        uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: ./flashcardapp
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4		
      - name: Install GTK4 and make app
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev; make flashcardapp
              
      - name: Run Tests
        run: ./test_quiz; ./test_storage
        
      - name: Upload Test Scrips
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./test_quiz; ./test_storage

      - name: Upload Gcov Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: ./*.gcov
